# Generated by Django 4.0 on 2023-11-26 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PyTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='問題')),
                ('ans', models.TextField(max_length=500, verbose_name='答え')),
                ('content', models.TextField(max_length=500, verbose_name='内容')),
            ],
        ),
    ]
